name: CI workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9-slim

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          flake8 src --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 src --count --max-complexity=10 --max-line-length=127 --statistics
      - name: Run unit tests with nose
        run:
          nosetests -v --with-spec --spec-color --with-coverage --cover-package=app
      - name: Install Sphinx
        run:
          pip install -U sphinx
      - name: Setup for Documentation
        run: |
          mkdir docs
          cd docs
          sphinx-quickstart -q -p srcDocumentation -a renm10 --ext-autodoc --ext-viewcode -l en
          cd ..
          sphinx-apidoc -o docs src

# Under conf.py
# import os,sys

# sys.path.insert(0, os.path.abspath('..'))
# sys.path.append(os.path.abspath(
#    os.path.join(__file__, "../../src")
# ))

# Under index.rst 's  toctree
# modules